site_name: Resampler Flags
site_url: https://Lauren042.github.io/ResamplerDocs

nav:
    - About: index.md
    - Tools: tools.md
    - resampler.exe: flags.md
    - Doppelter: doppelter.md
    - Moresampler: moresampler.md
    - tn_fnds.exe: tn_fnds.md


theme:
    name: material
    font:
        text: Roboto
        code: IBM Plex Mono — Regular
    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle: 
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle: 
        icon: material/weather-sunny
        name: Switch to light mode

    features:
    - navigation.tracking
    - toc.integrate
    
markdown_extensions:
  - abbr
  - admonition
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
